/**
 * @file PageConstant.ets
 * @author liyi
 * @date 2024/10/26
 * @description 描述文件的功能
 */
export class PageConstant {
  static readonly HOME_CONTENT: string = 'HomeContent'
  static readonly HOME_PAGE_ORDER:string = 'PageOrder'
  static readonly DEVICE_CONNECT: string = 'DeviceConnect'
  static readonly INPUT_DIALOG: string = 'InputDialog'
  static readonly INPUT_DIALOG_MUSIC: string = 'InputMusicDialog'
  static readonly INPUT_DIALOG_STO: string = 'InputStoDialog'
  static readonly SHOW_CONTENT_DIALOG: string = 'ShowContentDialog'

  static readonly PAGE_EXERCISE: string = 'PageExercise'
  static readonly PAGE_HR_WARN_PARA: string = 'PageHrWarnPara'
  static readonly PAGE_USER_INFO: string = 'PageUserInfo'
  static readonly PAGE_HRLEVEL_PARA: string = 'PageHrLevelPara'
  static readonly PAGE_DND_PARA: string = 'PageDndPara'
  static readonly PAGE_DRINK_WATER_PARA: string = 'PageDrinkWaterPara'
  static readonly PAGE_SEDENTARY_PARA: string = 'PageSedentaryPara'
  static readonly PAGE_HR_CHECK_PARA: string = 'PageHrCheckPara'
  static readonly PAGE_LIFT_WRIST_PARA: string = 'PageLiftWristPara'
  static readonly PAGE_SPORT_TARGET_PARA: string = 'PageSportTargetPara'
  static readonly PAGE_WEATHER_PARA: string = 'PageWeatherPara'
  static readonly PAGE_WEATHER_DETAIL_PARA: string = 'PageWeatherDetailPara'
  static readonly PAGE_APP_MSG_PUSH_PARA: string = 'PageAppMsgPushPara'
  static readonly PAGE_ALARM_INFO: string = 'PageAlarmInfo'
  static readonly PAGE_PHONE_CALL: string = 'PagePhoneCall'
  static readonly PAGE_MUSIC: string = 'PageMusic'
  static readonly PAGE_SET_LOCAL: string = 'PageSetLocal'
  static readonly PAGE_QUICK_REPLY: string = 'PageQuickReply'
  static readonly PAGE_PHONE_BOOK: string = 'PagePhoneBook'
  static readonly PAGE_GET_FLASH_DATA: string = 'PageGetFlashData'
  static readonly PAGE_SET_AGPS_LOCAL: string = 'PageSetAgpsLocal'
  static readonly PAGE_PUSH_AGPS_DATA: string = 'PagePushAgpsData'
  static readonly PAGE_SET_SN_AND_CMEI: string = 'PageSetSnAndCmei'
  static readonly PAGE_NOTES_REMINDS: string = 'PageNotesReminds'

  static readonly PAGE_CUSTOM_DIAL: string = 'PageCustomDial'
  static readonly PAGE_CROP_IMAGE: string = 'PageCropImage'
  static readonly PAGE_ON_LINE_DIAL: string = 'PageOnLineDial'

  static readonly PAGE_CLIP_IMAGE: string = 'PageClipImage'

}